services:
  redis:
    image: redis:latest
    container_name: redis_weather
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:

networks:
  redis-network: